### ISSUE TITLE
[권욱제] Where is the perf binary path?

### ISSUE THREAD

**Issue by wookje** [kosslab-kr/linux-perf#5]
https://github.com/kosslab-kr/linux-perf/issues/2 를 따라서 진행하고 있는데

perf binary가 있는 경로가 /usr/local/bin/perf에도 없고 다른 폴더에서도 찾기 힘드네요...

**Comment by Taeung** [comment]
perf바이너리는 리눅스커널소스 받은거(tip저장소를 git clone한 내용)에서 tools/perf 들어가서 make명령으로 만들자나요 ? 그 경로 그대로 적어서 하면 되요. 예를 들어서 /home/taeung/git/linux/tools/perf/ 에서 make해서 perf 바이너리 만들었으면
`sudo uftrace record -t 1us -D 4 /home/taeung/git/linux/tools/perf/perf config`
가 되는거죠 !!

**Comment by Taeung** [comment]
훌륭합니다. 아직은 부담스러울수있는데 소스분석을 시도하시다니 화이팅 입니다. :+1:

**Comment by wookje** [comment]
어쩐지 안 될리가 없는데 경로를 오타 냈었네요...!! 감사합니다
